// <auto-generated />
using FL.Basecode.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FL.Basecode.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109130820_AddIconsTable")]
    partial class AddIconsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FL.Basecode.Data.Models.mAccounts", b =>
                {
                    b.Property<string>("acctId")
                        .HasColumnType("TEXT");

                    b.Property<int>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("currentBalance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("iconId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("initialBalance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("acctId");

                    b.HasIndex("iconId");

                    b.HasIndex("userId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FL.Basecode.Data.Models.mUsers", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.Property<int>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("lastLogin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mIcons", b =>
                {
                    b.Property<string>("iconId")
                        .HasColumnType("TEXT");

                    b.Property<int>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("iconName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("iconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("iconId");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("FL.Basecode.Data.Models.mAccounts", b =>
                {
                    b.HasOne("mIcons", "Icons")
                        .WithMany("Accounts")
                        .HasForeignKey("iconId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FL.Basecode.Data.Models.mUsers", "Users")
                        .WithMany("Accounts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icons");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FL.Basecode.Data.Models.mUsers", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("mIcons", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
